const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';
const REGISTER = 'REGISTER';
// const SET_CURRENT_USER = 'SET_CURRENT_USER';

// Competitions action type
const GET_ALL_COMPETITIONS = 'GET_ALL_COMPETITIONS';
const GET_FEATURED_COMPETITIONS = 'GET_FEATURED_COMPETITIONS';
const GET_ARCHIVED_COMPETITIONS = 'GET_ARCHIVED_COMPETITIONS';
const GET_MINE_COMPETITIONS = 'GET_MINE_COMPETITIONS';
const SET_CURRENT_ALL_COMPETITIONS = 'SET_CURRENT_ALL_COMPETITIONS';
const SET_CURRENT_FEATURED_COMPETITIONS = 'SET_CURRENT_FEATURED_COMPETITIONS';
const SET_CURRENT_ARCHIVED_COMPETITIONS = 'SET_CURRENT_ARCHIVED_COMPETITIONS';
const CLEAR_CURRENT_ALL_COMPETITIONS = 'CLEAR_CURRENT_ALL_COMPETITIONS';
const CLEAR_CURRENT_FEATURED_COMPETITIONS =
  'CLEAR_CURRENT_FEATURED_COMPETITIONS';
const CLEAR_CURRENT_ARCHIVED_COMPETITIONS =
  'CLEAR_CURRENT_ARCHIVED_COMPETITIONS';
export {
  LOGIN,
  LOGOUT,
  REGISTER,
  GET_ALL_COMPETITIONS,
  GET_FEATURED_COMPETITIONS,
  GET_ARCHIVED_COMPETITIONS,
  GET_MINE_COMPETITIONS,
  SET_CURRENT_ALL_COMPETITIONS,
  SET_CURRENT_FEATURED_COMPETITIONS,
  SET_CURRENT_ARCHIVED_COMPETITIONS,
  CLEAR_CURRENT_ALL_COMPETITIONS,
  CLEAR_CURRENT_FEATURED_COMPETITIONS,
  CLEAR_CURRENT_ARCHIVED_COMPETITIONS
};
