const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';
const REGISTER = 'REGISTER';
// const SET_CURRENT_USER = 'SET_CURRENT_USER';

// Contextual Donation
export const SET_CONTEXT = 'SET_CONTEXT';
export const SET_GIFT_CONTEXT_DETAILS = 'SET_GIFT_CONTEXT_DETAILS';
export const SET_SUPPORT_DETAILS = 'SET_SUPPORT_DETAILS';
export const SET_PLEDGE_DETAILS = 'SET_PLEDGE_DETAILS';
export const SET_DONATION_DETAILS = 'SET_DONATION_DETAILS';
export const SET_DONOR_DETAILS = 'SET_DONOR_DETAILS';
export const SET_PAYMENT_RESPONSE = 'SET_PAYMENT_RESPONSE';
export const SET_PAYMENT_DETAILS = 'SET_PAYMENT_DETAILS';
export const CLEAR_DONATION_REDUCER = 'CLEAR_DONATION_REDUCER';

export { LOGIN, LOGOUT, REGISTER };
