const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';
const REGISTER = 'REGISTER';
// const SET_CURRENT_USER = 'SET_CURRENT_USER';

// Competitions action type
const GET_ALL_COMPETITIONS = 'GET_ALL_COMPETITIONS';
const GET_FEATURED_COMPETITIONS = 'GET_FEATURED_COMPETITIONS';
const GET_ARCHIVED_COMPETITIONS = 'GET_ARCHIVED_COMPETITIONS';
export {
  LOGIN,
  LOGOUT,
  REGISTER,
  GET_ALL_COMPETITIONS,
  GET_FEATURED_COMPETITIONS,
  GET_ARCHIVED_COMPETITIONS
};
