export const formStrings = {
  forgotPassword: 'Forgot Password?',  
  createAccount: 'New User? ',
  register: 'Register',
  seeMore: 'see more',
  donateTrees: 'donate trees',
  planted: 'Planted',
  treeCost: 'Tree Cost',
  certified: 'Certified',
  nonCertified: 'Non-Certified',
  target: 'Target',
  previouslyDonated: 'Previously Donated',
  featuredProjects: 'Featured Projects',
  paypal: 'Paypal',
  redirectionMessage: '(You will be redirected to Paypal.)',
  directDebit: 'Direct Debit',
  IBAN: 'IBAN',
  BIC: 'BIC',
  creditCard: 'Credit Card',
  creditCardMessage: '(We accept Visa and MasterCard for 15,00 € and above.)',
  donateTreesMessage: 'Any trees donated will count towards your personal tree counter.',
  selectDifferentProject: 'Select Different Project',
  costPerTree: 'CostPerTree',
  project: 'Project',
  organisation: 'Organisation',
  Cost: 'Cost Per Tree',
  menu: 'menu',
  signUp: 'Sign Up',
  logIn: 'Log In',
  home: 'home',
  search: 'search',
  registerPlantedTrees: 'Register Planted Trees',
  individual: 'Individual',
  many: 'Many',
  survival_rate: 'Survival Rate',
  singleTree: 'Single Tree',
  severalTrees: 'Several Trees',
  registerFurther: "REGISTER FURTHER TREES",
  DONATETREES: 'DONATE TREES',
  noContributions: 'No Contributions'
}