export default {
  title: 'donation_contribution',
  type: 'object',
  properties: {
    treeCount: {
      type: 'number',
      title: 'label.tree_count',
      icon: null,
      help: null,
      propertyOrder: 1
    },
    amount: {
      type: 'number',
      title: 'label.amount',
      icon: null,
      help: null,
      propertyOrder: 2
    },
    currency: {
      type: 'string',
      title: 'label.currency',
      attr: {
        maxlength: 3
      },
      icon: null,
      help: null,
      maxLength: 3,
      propertyOrder: 3
    },
    paymentResponse: {
      type: 'hidden',
      title: 'label.payment_method',
      widget: 'hidden',
      icon: null,
      help: null,
      propertyOrder: 4
    },
    recipientType: {
      type: 'string',
      title: null,
      icon: null,
      help: null,
      propertyOrder: 5
    },
    receiptIndividual: {
      title: null,
      type: 'object',
      properties: {
        firstname: {
          type: 'string',
          title: 'label.firstname',
          attr: {
            maxlength: 50,
            pattern: '.{2,}'
          },
          pattern: '.{2,}',
          icon: 'userAvtar',
          help: null,
          maxLength: 50,
          minLength: 2,
          propertyOrder: 1
        },
        lastname: {
          type: 'string',
          title: 'label.lastname',
          attr: {
            maxlength: 50,
            pattern: '.{2,}'
          },
          pattern: '.{2,}',
          icon: 'userAvtar',
          help: null,
          maxLength: 50,
          minLength: 2,
          propertyOrder: 2
        },
        email: {
          type: 'string',
          title: 'label.email',
          attr: {
            maxlength: 50
          },
          widget: 'email',
          icon: 'email',
          help: null,
          maxLength: 50,
          propertyOrder: 3
        },
        address: {
          type: 'string',
          title: 'label.address',
          attr: {
            maxlength: 255
          },
          icon: 'home',
          help: null,
          maxLength: 255,
          propertyOrder: 4
        },
        zipCode: {
          type: 'string',
          title: 'label.zipCode',
          attr: {
            maxlength: 15
          },
          icon: null,
          help: null,
          maxLength: 15,
          propertyOrder: 5
        },
        city: {
          type: 'string',
          title: 'label.city',
          attr: {
            maxlength: 255
          },
          icon: null,
          help: null,
          maxLength: 255,
          propertyOrder: 6
        },
        country: {
          enum: [
            'AF',
            'AX',
            'AL',
            'DZ',
            'AS',
            'AD',
            'AO',
            'AI',
            'AQ',
            'AG',
            'AR',
            'AM',
            'AW',
            'AC',
            'AU',
            'AT',
            'AZ',
            'BS',
            'BH',
            'BD',
            'BB',
            'BY',
            'BE',
            'BZ',
            'BJ',
            'BM',
            'BT',
            'BO',
            'BA',
            'BW',
            'BR',
            'IO',
            'VG',
            'BN',
            'BG',
            'BF',
            'BI',
            'KH',
            'CM',
            'CA',
            'IC',
            'CV',
            'BQ',
            'KY',
            'CF',
            'EA',
            'TD',
            'CL',
            'CN',
            'CX',
            'CC',
            'CO',
            'KM',
            'CG',
            'CD',
            'CK',
            'CR',
            'CI',
            'HR',
            'CU',
            'CW',
            'CY',
            'CZ',
            'DK',
            'DG',
            'DJ',
            'DM',
            'DO',
            'EC',
            'EG',
            'SV',
            'GQ',
            'ER',
            'EE',
            'ET',
            'EZ',
            'FK',
            'FO',
            'FJ',
            'FI',
            'FR',
            'GF',
            'PF',
            'TF',
            'GA',
            'GM',
            'GE',
            'DE',
            'GH',
            'GI',
            'GR',
            'GL',
            'GD',
            'GP',
            'GU',
            'GT',
            'GG',
            'GN',
            'GW',
            'GY',
            'HT',
            'HN',
            'HK',
            'HU',
            'IS',
            'IN',
            'ID',
            'IR',
            'IQ',
            'IE',
            'IM',
            'IL',
            'IT',
            'JM',
            'JP',
            'JE',
            'JO',
            'KZ',
            'KE',
            'KI',
            'XK',
            'KW',
            'KG',
            'LA',
            'LV',
            'LB',
            'LS',
            'LR',
            'LY',
            'LI',
            'LT',
            'LU',
            'MO',
            'MK',
            'MG',
            'MW',
            'MY',
            'MV',
            'ML',
            'MT',
            'MH',
            'MQ',
            'MR',
            'MU',
            'YT',
            'MX',
            'FM',
            'MD',
            'MC',
            'MN',
            'ME',
            'MS',
            'MA',
            'MZ',
            'MM',
            'NA',
            'NR',
            'NP',
            'NL',
            'NC',
            'NZ',
            'NI',
            'NE',
            'NG',
            'NU',
            'NF',
            'KP',
            'MP',
            'NO',
            'OM',
            'PK',
            'PW',
            'PS',
            'PA',
            'PG',
            'PY',
            'PE',
            'PH',
            'PN',
            'PL',
            'PT',
            'PR',
            'QA',
            'RE',
            'RO',
            'RU',
            'RW',
            'WS',
            'SM',
            'ST',
            'SA',
            'SN',
            'RS',
            'SC',
            'SL',
            'SG',
            'SX',
            'SK',
            'SI',
            'SB',
            'SO',
            'ZA',
            'GS',
            'KR',
            'SS',
            'ES',
            'LK',
            'BL',
            'SH',
            'KN',
            'LC',
            'MF',
            'PM',
            'VC',
            'SD',
            'SR',
            'SJ',
            'SZ',
            'SE',
            'CH',
            'SY',
            'TW',
            'TJ',
            'TZ',
            'TH',
            'TL',
            'TG',
            'TK',
            'TO',
            'TT',
            'TA',
            'TN',
            'TR',
            'TM',
            'TC',
            'TV',
            'UM',
            'VI',
            'UG',
            'UA',
            'AE',
            'GB',
            'UN',
            'US',
            'UY',
            'UZ',
            'VU',
            'VA',
            'VE',
            'VN',
            'WF',
            'EH',
            'YE',
            'ZM',
            'ZW'
          ],
          enum_titles: [
            'country.af',
            'country.ax',
            'country.al',
            'country.dz',
            'country.as',
            'country.ad',
            'country.ao',
            'country.ai',
            'country.aq',
            'country.ag',
            'country.ar',
            'country.am',
            'country.aw',
            'country.ac',
            'country.au',
            'country.at',
            'country.az',
            'country.bs',
            'country.bh',
            'country.bd',
            'country.bb',
            'country.by',
            'country.be',
            'country.bz',
            'country.bj',
            'country.bm',
            'country.bt',
            'country.bo',
            'country.ba',
            'country.bw',
            'country.br',
            'country.io',
            'country.vg',
            'country.bn',
            'country.bg',
            'country.bf',
            'country.bi',
            'country.kh',
            'country.cm',
            'country.ca',
            'country.ic',
            'country.cv',
            'country.bq',
            'country.ky',
            'country.cf',
            'country.ea',
            'country.td',
            'country.cl',
            'country.cn',
            'country.cx',
            'country.cc',
            'country.co',
            'country.km',
            'country.cg',
            'country.cd',
            'country.ck',
            'country.cr',
            'country.ci',
            'country.hr',
            'country.cu',
            'country.cw',
            'country.cy',
            'country.cz',
            'country.dk',
            'country.dg',
            'country.dj',
            'country.dm',
            'country.do',
            'country.ec',
            'country.eg',
            'country.sv',
            'country.gq',
            'country.er',
            'country.ee',
            'country.et',
            'country.ez',
            'country.fk',
            'country.fo',
            'country.fj',
            'country.fi',
            'country.fr',
            'country.gf',
            'country.pf',
            'country.tf',
            'country.ga',
            'country.gm',
            'country.ge',
            'country.de',
            'country.gh',
            'country.gi',
            'country.gr',
            'country.gl',
            'country.gd',
            'country.gp',
            'country.gu',
            'country.gt',
            'country.gg',
            'country.gn',
            'country.gw',
            'country.gy',
            'country.ht',
            'country.hn',
            'country.hk',
            'country.hu',
            'country.is',
            'country.in',
            'country.id',
            'country.ir',
            'country.iq',
            'country.ie',
            'country.im',
            'country.il',
            'country.it',
            'country.jm',
            'country.jp',
            'country.je',
            'country.jo',
            'country.kz',
            'country.ke',
            'country.ki',
            'country.xk',
            'country.kw',
            'country.kg',
            'country.la',
            'country.lv',
            'country.lb',
            'country.ls',
            'country.lr',
            'country.ly',
            'country.li',
            'country.lt',
            'country.lu',
            'country.mo',
            'country.mk',
            'country.mg',
            'country.mw',
            'country.my',
            'country.mv',
            'country.ml',
            'country.mt',
            'country.mh',
            'country.mq',
            'country.mr',
            'country.mu',
            'country.yt',
            'country.mx',
            'country.fm',
            'country.md',
            'country.mc',
            'country.mn',
            'country.me',
            'country.ms',
            'country.ma',
            'country.mz',
            'country.mm',
            'country.na',
            'country.nr',
            'country.np',
            'country.nl',
            'country.nc',
            'country.nz',
            'country.ni',
            'country.ne',
            'country.ng',
            'country.nu',
            'country.nf',
            'country.kp',
            'country.mp',
            'country.no',
            'country.om',
            'country.pk',
            'country.pw',
            'country.ps',
            'country.pa',
            'country.pg',
            'country.py',
            'country.pe',
            'country.ph',
            'country.pn',
            'country.pl',
            'country.pt',
            'country.pr',
            'country.qa',
            'country.re',
            'country.ro',
            'country.ru',
            'country.rw',
            'country.ws',
            'country.sm',
            'country.st',
            'country.sa',
            'country.sn',
            'country.rs',
            'country.sc',
            'country.sl',
            'country.sg',
            'country.sx',
            'country.sk',
            'country.si',
            'country.sb',
            'country.so',
            'country.za',
            'country.gs',
            'country.kr',
            'country.ss',
            'country.es',
            'country.lk',
            'country.bl',
            'country.sh',
            'country.kn',
            'country.lc',
            'country.mf',
            'country.pm',
            'country.vc',
            'country.sd',
            'country.sr',
            'country.sj',
            'country.sz',
            'country.se',
            'country.ch',
            'country.sy',
            'country.tw',
            'country.tj',
            'country.tz',
            'country.th',
            'country.tl',
            'country.tg',
            'country.tk',
            'country.to',
            'country.tt',
            'country.ta',
            'country.tn',
            'country.tr',
            'country.tm',
            'country.tc',
            'country.tv',
            'country.um',
            'country.vi',
            'country.ug',
            'country.ua',
            'country.ae',
            'country.gb',
            'country.un',
            'country.us',
            'country.uy',
            'country.uz',
            'country.vu',
            'country.va',
            'country.ve',
            'country.vn',
            'country.wf',
            'country.eh',
            'country.ye',
            'country.zm',
            'country.zw'
          ],
          type: 'string',
          title: 'label.country',
          icon: null,
          help: null,
          propertyOrder: 7
        }
      },
      required: [
        'firstname',
        'lastname',
        'email',
        'address',
        'zipCode',
        'city',
        'country'
      ],
      icon: null,
      help: null,
      propertyOrder: 6
    },
    receiptCompany: {
      title: null,
      type: 'object',
      properties: {
        companyname: {
          type: 'string',
          title: 'label.company_or_orga_name',
          attr: {
            maxlength: 255
          },
          icon: null,
          help: null,
          maxLength: 255,
          propertyOrder: 1
        },
        firstname: {
          type: 'string',
          title: 'label.contact_firstname',
          attr: {
            maxlength: 50,
            pattern: '.{2,}'
          },
          pattern: '.{2,}',
          icon: 'userAvtar',
          help: null,
          maxLength: 50,
          minLength: 2,
          propertyOrder: 2
        },
        lastname: {
          type: 'string',
          title: 'label.contact_lastname',
          attr: {
            maxlength: 50,
            pattern: '.{2,}'
          },
          pattern: '.{2,}',
          icon: 'userAvtar',
          help: null,
          maxLength: 50,
          minLength: 2,
          propertyOrder: 3
        },
        email: {
          type: 'string',
          title: 'label.email',
          attr: {
            maxlength: 50
          },
          widget: 'email',
          icon: 'email',
          help: null,
          maxLength: 50,
          propertyOrder: 4
        },
        address: {
          type: 'string',
          title: 'label.address',
          attr: {
            maxlength: 255
          },
          icon: 'home',
          help: null,
          maxLength: 255,
          propertyOrder: 5
        },
        zipCode: {
          type: 'string',
          title: 'label.zipCode',
          attr: {
            maxlength: 15
          },
          icon: null,
          help: null,
          maxLength: 15,
          propertyOrder: 6
        },
        city: {
          type: 'string',
          title: 'label.city',
          attr: {
            maxlength: 255
          },
          icon: null,
          help: null,
          maxLength: 255,
          propertyOrder: 7
        },
        country: {
          enum: [
            'AF',
            'AX',
            'AL',
            'DZ',
            'AS',
            'AD',
            'AO',
            'AI',
            'AQ',
            'AG',
            'AR',
            'AM',
            'AW',
            'AC',
            'AU',
            'AT',
            'AZ',
            'BS',
            'BH',
            'BD',
            'BB',
            'BY',
            'BE',
            'BZ',
            'BJ',
            'BM',
            'BT',
            'BO',
            'BA',
            'BW',
            'BR',
            'IO',
            'VG',
            'BN',
            'BG',
            'BF',
            'BI',
            'KH',
            'CM',
            'CA',
            'IC',
            'CV',
            'BQ',
            'KY',
            'CF',
            'EA',
            'TD',
            'CL',
            'CN',
            'CX',
            'CC',
            'CO',
            'KM',
            'CG',
            'CD',
            'CK',
            'CR',
            'CI',
            'HR',
            'CU',
            'CW',
            'CY',
            'CZ',
            'DK',
            'DG',
            'DJ',
            'DM',
            'DO',
            'EC',
            'EG',
            'SV',
            'GQ',
            'ER',
            'EE',
            'ET',
            'EZ',
            'FK',
            'FO',
            'FJ',
            'FI',
            'FR',
            'GF',
            'PF',
            'TF',
            'GA',
            'GM',
            'GE',
            'DE',
            'GH',
            'GI',
            'GR',
            'GL',
            'GD',
            'GP',
            'GU',
            'GT',
            'GG',
            'GN',
            'GW',
            'GY',
            'HT',
            'HN',
            'HK',
            'HU',
            'IS',
            'IN',
            'ID',
            'IR',
            'IQ',
            'IE',
            'IM',
            'IL',
            'IT',
            'JM',
            'JP',
            'JE',
            'JO',
            'KZ',
            'KE',
            'KI',
            'XK',
            'KW',
            'KG',
            'LA',
            'LV',
            'LB',
            'LS',
            'LR',
            'LY',
            'LI',
            'LT',
            'LU',
            'MO',
            'MK',
            'MG',
            'MW',
            'MY',
            'MV',
            'ML',
            'MT',
            'MH',
            'MQ',
            'MR',
            'MU',
            'YT',
            'MX',
            'FM',
            'MD',
            'MC',
            'MN',
            'ME',
            'MS',
            'MA',
            'MZ',
            'MM',
            'NA',
            'NR',
            'NP',
            'NL',
            'NC',
            'NZ',
            'NI',
            'NE',
            'NG',
            'NU',
            'NF',
            'KP',
            'MP',
            'NO',
            'OM',
            'PK',
            'PW',
            'PS',
            'PA',
            'PG',
            'PY',
            'PE',
            'PH',
            'PN',
            'PL',
            'PT',
            'PR',
            'QA',
            'RE',
            'RO',
            'RU',
            'RW',
            'WS',
            'SM',
            'ST',
            'SA',
            'SN',
            'RS',
            'SC',
            'SL',
            'SG',
            'SX',
            'SK',
            'SI',
            'SB',
            'SO',
            'ZA',
            'GS',
            'KR',
            'SS',
            'ES',
            'LK',
            'BL',
            'SH',
            'KN',
            'LC',
            'MF',
            'PM',
            'VC',
            'SD',
            'SR',
            'SJ',
            'SZ',
            'SE',
            'CH',
            'SY',
            'TW',
            'TJ',
            'TZ',
            'TH',
            'TL',
            'TG',
            'TK',
            'TO',
            'TT',
            'TA',
            'TN',
            'TR',
            'TM',
            'TC',
            'TV',
            'UM',
            'VI',
            'UG',
            'UA',
            'AE',
            'GB',
            'UN',
            'US',
            'UY',
            'UZ',
            'VU',
            'VA',
            'VE',
            'VN',
            'WF',
            'EH',
            'YE',
            'ZM',
            'ZW'
          ],
          enum_titles: [
            'country.af',
            'country.ax',
            'country.al',
            'country.dz',
            'country.as',
            'country.ad',
            'country.ao',
            'country.ai',
            'country.aq',
            'country.ag',
            'country.ar',
            'country.am',
            'country.aw',
            'country.ac',
            'country.au',
            'country.at',
            'country.az',
            'country.bs',
            'country.bh',
            'country.bd',
            'country.bb',
            'country.by',
            'country.be',
            'country.bz',
            'country.bj',
            'country.bm',
            'country.bt',
            'country.bo',
            'country.ba',
            'country.bw',
            'country.br',
            'country.io',
            'country.vg',
            'country.bn',
            'country.bg',
            'country.bf',
            'country.bi',
            'country.kh',
            'country.cm',
            'country.ca',
            'country.ic',
            'country.cv',
            'country.bq',
            'country.ky',
            'country.cf',
            'country.ea',
            'country.td',
            'country.cl',
            'country.cn',
            'country.cx',
            'country.cc',
            'country.co',
            'country.km',
            'country.cg',
            'country.cd',
            'country.ck',
            'country.cr',
            'country.ci',
            'country.hr',
            'country.cu',
            'country.cw',
            'country.cy',
            'country.cz',
            'country.dk',
            'country.dg',
            'country.dj',
            'country.dm',
            'country.do',
            'country.ec',
            'country.eg',
            'country.sv',
            'country.gq',
            'country.er',
            'country.ee',
            'country.et',
            'country.ez',
            'country.fk',
            'country.fo',
            'country.fj',
            'country.fi',
            'country.fr',
            'country.gf',
            'country.pf',
            'country.tf',
            'country.ga',
            'country.gm',
            'country.ge',
            'country.de',
            'country.gh',
            'country.gi',
            'country.gr',
            'country.gl',
            'country.gd',
            'country.gp',
            'country.gu',
            'country.gt',
            'country.gg',
            'country.gn',
            'country.gw',
            'country.gy',
            'country.ht',
            'country.hn',
            'country.hk',
            'country.hu',
            'country.is',
            'country.in',
            'country.id',
            'country.ir',
            'country.iq',
            'country.ie',
            'country.im',
            'country.il',
            'country.it',
            'country.jm',
            'country.jp',
            'country.je',
            'country.jo',
            'country.kz',
            'country.ke',
            'country.ki',
            'country.xk',
            'country.kw',
            'country.kg',
            'country.la',
            'country.lv',
            'country.lb',
            'country.ls',
            'country.lr',
            'country.ly',
            'country.li',
            'country.lt',
            'country.lu',
            'country.mo',
            'country.mk',
            'country.mg',
            'country.mw',
            'country.my',
            'country.mv',
            'country.ml',
            'country.mt',
            'country.mh',
            'country.mq',
            'country.mr',
            'country.mu',
            'country.yt',
            'country.mx',
            'country.fm',
            'country.md',
            'country.mc',
            'country.mn',
            'country.me',
            'country.ms',
            'country.ma',
            'country.mz',
            'country.mm',
            'country.na',
            'country.nr',
            'country.np',
            'country.nl',
            'country.nc',
            'country.nz',
            'country.ni',
            'country.ne',
            'country.ng',
            'country.nu',
            'country.nf',
            'country.kp',
            'country.mp',
            'country.no',
            'country.om',
            'country.pk',
            'country.pw',
            'country.ps',
            'country.pa',
            'country.pg',
            'country.py',
            'country.pe',
            'country.ph',
            'country.pn',
            'country.pl',
            'country.pt',
            'country.pr',
            'country.qa',
            'country.re',
            'country.ro',
            'country.ru',
            'country.rw',
            'country.ws',
            'country.sm',
            'country.st',
            'country.sa',
            'country.sn',
            'country.rs',
            'country.sc',
            'country.sl',
            'country.sg',
            'country.sx',
            'country.sk',
            'country.si',
            'country.sb',
            'country.so',
            'country.za',
            'country.gs',
            'country.kr',
            'country.ss',
            'country.es',
            'country.lk',
            'country.bl',
            'country.sh',
            'country.kn',
            'country.lc',
            'country.mf',
            'country.pm',
            'country.vc',
            'country.sd',
            'country.sr',
            'country.sj',
            'country.sz',
            'country.se',
            'country.ch',
            'country.sy',
            'country.tw',
            'country.tj',
            'country.tz',
            'country.th',
            'country.tl',
            'country.tg',
            'country.tk',
            'country.to',
            'country.tt',
            'country.ta',
            'country.tn',
            'country.tr',
            'country.tm',
            'country.tc',
            'country.tv',
            'country.um',
            'country.vi',
            'country.ug',
            'country.ua',
            'country.ae',
            'country.gb',
            'country.un',
            'country.us',
            'country.uy',
            'country.uz',
            'country.vu',
            'country.va',
            'country.ve',
            'country.vn',
            'country.wf',
            'country.eh',
            'country.ye',
            'country.zm',
            'country.zw'
          ],
          type: 'string',
          title: 'label.country',
          icon: null,
          help: null,
          propertyOrder: 8
        }
      },
      required: [
        'companyname',
        'firstname',
        'lastname',
        'email',
        'address',
        'zipCode',
        'city',
        'country'
      ],
      icon: null,
      help: null,
      propertyOrder: 7
    },
    communityTreecounter: {
      type: 'integer',
      title: 'label.supported_treecounter',
      widget: 'hidden',
      icon: null,
      help: null,
      propertyOrder: 8
    }
  },
  required: [
    'treeCount',
    'amount',
    'currency',
    'recipientType',
    'communityTreecounter'
  ],
  submit_url: '',
  submit_method: 'POST'
};
