export default {
  title: 'plantProject',
  type: 'object',
  properties: {
    name: {
      type: 'string',
      title: 'label.project_name',
      attr: {
        maxlength: 255
      },
      icon: null,
      help: null,
      maxLength: 255,
      propertyOrder: 1
    },
    countTarget: {
      type: 'number',
      title: 'label.count_target',
      icon: null,
      help: null,
      propertyOrder: 2
    },
    survivalRate: {
      type: 'integer',
      title: 'label.survival_rate',
      attr: {
        maxlength: 3,
        pattern: '.{1,}'
      },
      pattern: '.{1,}',
      icon: null,
      help: null,
      propertyOrder: 3
    },
    imageFile: {
      type: 'string',
      title: 'label.upload_profile_picture',
      widget: 'file',
      icon: null,
      help: null,
      propertyOrder: 4
    },
    treeCost: {
      type: 'number',
      title: 'label.tree_cost',
      icon: null,
      help: null,
      propertyOrder: 5
    },
    currency: {
      enum: [
        'EUR',
        'USD',
        'GBP',
        'AUD',
        'SGD',
        '',
        'ALL',
        'DZD',
        'AMD',
        'AWG',
        'AZN',
        'BSD',
        'BDT',
        'BBD',
        'BZD',
        'BMD',
        'BWP',
        'BND',
        'BGN',
        'KHR',
        'CAD',
        'KYD',
        'CNY',
        'CDF',
        'HRK',
        'DKK',
        'DOP',
        'XCD',
        'EGP',
        'ETB',
        'FJD',
        'GMD',
        'GEL',
        'GIP',
        'GYD',
        'HTG',
        'HKD',
        'ISK',
        'IDR',
        'ILS',
        'JMD',
        'KZT',
        'KES',
        'KGS',
        'LBP',
        'LSL',
        'LRD',
        'MOP',
        'MKD',
        'MWK',
        'MYR',
        'MVR',
        'MXN',
        'MDL',
        'MNT',
        'MAD',
        'MZN',
        'MMK',
        'NAD',
        'NPR',
        'ANG',
        'TWD',
        'NZD',
        'NGN',
        'NOK',
        'PKR',
        'PGK',
        'PHP',
        'PLN',
        'QAR',
        'RON',
        'RUB',
        'WST',
        'SAR',
        'RSD',
        'SCR',
        'SLL',
        'SBD',
        'SOS',
        'ZAR',
        'LKR',
        'SZL',
        'SEK',
        'CHF',
        'TJS',
        'TZS',
        'THB',
        'TOP',
        'TTD',
        'TRY',
        'UAH',
        'AED',
        'UZS',
        'YER',
        'ZMW'
      ],
      enum_titles: [
        'Euro',
        'US Dollar',
        'British Pound',
        'Australian Dollar',
        'Singapore Dollar',
        '--------------------',
        'Albanian Lek',
        'Algerian Dinar',
        'Armenian Dram',
        'Aruban Florin',
        'Azerbaijani Manat',
        'Bahamian Dollar',
        'Bangladeshi Taka',
        'Barbadian Dollar',
        'Belize Dollar',
        'Bermudan Dollar',
        'Botswanan Pula',
        'Brunei Dollar',
        'Bulgarian Lev',
        'Cambodian Riel',
        'Canadian Dollar',
        'Cayman Islands Dollar',
        'Chinese Yuan',
        'Congolese Franc',
        'Croatian Kuna',
        'Danish Krone',
        'Dominican Peso',
        'East Caribbean Dollar',
        'Egyptian Pound',
        'Ethiopian Birr',
        'Fijian Dollar',
        'Gambian Dalasi',
        'Georgian Lari',
        'Gibraltar Pound',
        'Guyanaese Dollar',
        'Haitian Gourde',
        'Hong Kong Dollar',
        'Icelandic Króna',
        'Indonesian Rupiah',
        'Israeli New Shekel',
        'Jamaican Dollar',
        'Kazakhstani Tenge',
        'Kenyan Shilling',
        'Kyrgystani Som',
        'Lebanese Pound',
        'Lesotho Loti',
        'Liberian Dollar',
        'Macanese Pataca',
        'Macedonian Denar',
        'Malawian Kwacha',
        'Malaysian Ringgit',
        'Maldivian Rufiyaa',
        'Mexican Peso',
        'Moldovan Leu',
        'Mongolian Tugrik',
        'Moroccan Dirham',
        'Mozambican Metical',
        'Myanmar Kyat',
        'Namibian Dollar',
        'Nepalese Rupee',
        'Netherlands Antillean Guilder',
        'New Taiwan Dollar',
        'New Zealand Dollar',
        'Nigerian Naira',
        'Norwegian Krone',
        'Pakistani Rupee',
        'Papua New Guinean Kina',
        'Philippine Piso',
        'Polish Zloty',
        'Qatari Rial',
        'Romanian Leu',
        'Russian Ruble',
        'Samoan Tala',
        'Saudi Riyal',
        'Serbian Dinar',
        'Seychellois Rupee',
        'Sierra Leonean Leone',
        'Solomon Islands Dollar',
        'Somali Shilling',
        'South African Rand',
        'Sri Lankan Rupee',
        'Swazi Lilangeni',
        'Swedish Krona',
        'Swiss Franc',
        'Tajikistani Somoni',
        'Tanzanian Shilling',
        'Thai Baht',
        'Tongan Paʻanga',
        'Trinidad & Tobago Dollar',
        'Turkish Lira',
        'Ukrainian Hryvnia',
        'United Arab Emirates Dirham',
        'Uzbekistani Som',
        'Yemeni Rial',
        'Zambian Kwacha'
      ],
      type: 'string',
      title: 'label.currency',
      icon: null,
      help: null,
      propertyOrder: 6
    },
    location: {
      type: 'string',
      title: 'label.location',
      widget: 'textarea',
      icon: null,
      help: null,
      propertyOrder: 7
    },
    geoLocation: {
      type: 'string',
      title: 'label.geo_location',
      widget: 'map',
      icon: null,
      help: null,
      propertyOrder: 8
    },
    description: {
      type: 'string',
      title: 'label.description',
      widget: 'textarea',
      icon: null,
      help: null,
      propertyOrder: 9
    },
    url: {
      type: 'string',
      title: 'label.url',
      widget: 'textarea',
      icon: null,
      help: null,
      propertyOrder: 10
    },
    linkText: {
      type: 'string',
      title: 'label.link_text',
      widget: 'textarea',
      icon: null,
      help: null,
      propertyOrder: 11
    },
    plantProjectImages: {
      type: 'array',
      title: 'label.add_images',
      items: {
        title: 'prototype',
        type: 'object',
        properties: {
          image: {
            type: 'string',
            title: 'label.upload_profile_picture',
            widget: 'file',
            icon: null,
            help: null,
            propertyOrder: 1
          },
          description: {
            type: 'string',
            title: null,
            widget: 'textarea',
            icon: null,
            help: null,
            propertyOrder: 2
          },
          id: {
            type: 'number',
            title: null,
            widget: 'hidden',
            icon: null,
            help: null,
            propertyOrder: 3
          }
        },
        required: ['imageFile'],
        icon: null,
        help: null
      },
      icon: null,
      help: null,
      propertyOrder: 12
    },
    videoUrl: {
      type: 'string',
      title: 'label.video_url',
      widget: 'textarea',
      icon: null,
      help: null,
      propertyOrder: 13
    }
  },
  required: ['name', 'treeCost', 'currency', 'geoLocation'],
  submit_url: '',
  submit_method: 'POST'
};
