# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TreecounterApp' do
  inherit! :search_paths
  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

end
