const projectDonateIds = [
  { value: 67, name: '20 Million Trees for Kenya’s Forests' },
  { value: 84, name: 'A Million Trees for Ireland' },
  { value: 109, name: 'Acadian Forest Restoration' },
  { value: 97, name: 'Acción Andina - Andes Action' },
  { value: 62, name: 'Adopt a Tree' },
  { value: 117, name: 'Beautiful Bengaluru' },
  { value: 122, name: 'BeeTree2' },
  { value: 87, name: 'CEJ Reforestation Project' },
  { value: 65, name: 'Coastal Reforestation in Taiwan' },
  { value: 76, name: 'Coffee Farming as an Alternative Livelihood' },
  { value: 113, name: 'Courtown Harbour Restoration' },
  { value: 94, name: 'Eden Reforestation Projects' },
  { value: 114, name: 'Fifty Tree Campangian' },
  { value: 105, name: 'Forest Nation' },
  { value: 72, name: 'Greenbelt Mumbai' },
  { value: 106, name: 'Greening and Conserving for the future' },
  { value: 121, name: 'Greening Burundi Project' },
  { value: 90, name: 'Greening Uganda' },
  { value: 86, name: 'JCI Forest' },
  { value: 110, name: 'Jeji Restoration' },
  {
    value: 96,
    name: 'Kadhune Friends of Earth Environment Preservation and Care'
  },
  { value: 92, name: 'Königswald Ontananga' },
  { value: 46, name: 'LIMBUA Tree Nursery' },
  { value: 107, name: 'Mangrove Restoration on Pemba Island' },
  { value: 108, name: 'Mphompha Planting Trees project' },
  { value: 100, name: 'Njuguna John Planting Project' },
  { value: 99, name: 'One student One tree' },
  { value: 120, name: 'Permanent Plantation Station – Ejulve' },
  { value: 78, name: 'Piensa Alimentate Evoluciona' },
  { value: 80, name: 'Platbos Reforestation Project' },
  { value: 112, name: 'Pomarium Gut Wulfsdorf' },
  { value: 71, name: 'Projet de reboisement POROH VERT' },
  { value: 88, name: 'Projeto Pomar' },
  { value: 75, name: 'Reforestation and enrichment planting' },
  { value: 83, name: 'Reforestation and environmental education' },
  {
    value: 103,
    name:
      'Reforestation for communities staying around Mt. Rwenzori Forest National Park'
  },
  { value: 74, name: 'Reforestemos Centro Sur' },
  { value: 73, name: 'Reforestemos Patagonia' },
  { value: 70, name: 'Regenerating forests for Khasi communities' },
  {
    value: 119,
    name: 'Replanting trees to the Burnt Magila Natural Forest Reserve'
  },
  { value: 69, name: 'Reversing deforestation for smallholder farmers' },
  { value: 116, name: 'Seed Malawi' },
  { value: 85, name: 'Sinal do Vale' },
  { value: 81, name: 'Sustainable Community Forestry Programme' },
  { value: 77, name: 'Sustainable Timber and Household Woodlots' },
  { value: 66, name: 'The Give a Ghaf Tree Planting Program' },
  { value: 59, name: 'The Green Caravan' },
  { value: 60, name: 'The Million Tree Campaigns (MTC)' },
  { value: 82, name: 'Tree planting for Biodiversity conservation' },
  { value: 95, name: 'Tree, the Solution' },
  { value: 47, name: ' Trees by KDA' },
  { value: 34, name: 'Trees for Peace - An AYUDH Europe campaign' },
  { value: 49, name: 'Trees4Trees' },
  { value: 104, name: 'Ültess fát a jövőért - Plant for the future' },
  { value: 68, name: 'Wildlife corridors for the Atlantic Forest' },
  { value: 1, name: 'Yucatán Reforestation' }
];

export default projectDonateIds;
